skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
week2_vault = "6Dm3EYsvKi52MqWw8qRB3upUqHHj6w73wAvGhYiYvpAR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
